/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minibattle;

import minibattle.creature.Creature;

public class MiniBattle {

    public static void main(String[] args) {
        System.out.println(new Creature("Potato Knight"));
        System.out.println("VS.");
        System.out.println(new Creature("Onion Knight"));
    }
}
